"""add external_url and bid_ord

Revision ID: 3a5e7dd310fd
Revises: ea411d5d0985
Create Date: 2026-04-28 11:50:02.163571
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '3a5e7dd310fd'
down_revision: Union[str, None] = 'ea411d5d0985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid_announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bid_ord', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid_announcements', schema=None) as batch_op:
        batch_op.drop_column('bid_ord')
        batch_op.drop_column('external_url')

    # ### end Alembic commands ###
