"""DataSyncLog progress fields

Revision ID: c0827aa6f216
Revises: 3a5e7dd310fd
Create Date: 2026-05-06 16:14:19.873365
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'c0827aa6f216'
down_revision: Union[str, None] = '3a5e7dd310fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_cursor_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sync_logs', schema=None) as batch_op:
        batch_op.drop_column('last_cursor_date')
        batch_op.drop_column('last_page')
        batch_op.drop_column('progress_pct')

    # ### end Alembic commands ###
