"""initial schema

Revision ID: e39567e2e121
Revises: 
Create Date: 2026-04-24 13:38:58.889758
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e39567e2e121'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inserted_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sync_logs', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('inserted_count')

    # ### end Alembic commands ###
