"""add is_defense flag

Revision ID: ea411d5d0985
Revises: e39567e2e121
Create Date: 2026-04-27 15:32:12.804628
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ea411d5d0985'
down_revision: Union[str, None] = 'e39567e2e121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid_announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_defense', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bid_announcements_is_defense'), ['is_defense'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid_announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bid_announcements_is_defense'))
        batch_op.drop_column('is_defense')

    # ### end Alembic commands ###
